<?php
$myCollect['sitename'] = "好租测试";
$myCollect['siteurl'] = "http://chengdu.haozu.com/";
$myCollect['modid'] = "7";
$myCollect['apiname'] = "";
$myCollect['proxy_host'] = "";
$myCollect['proxy_port'] = "";
$myCollect['verify_mode'] = "2";
$myCollect['spider_auth'] = "123456";
$myCollect['spider_ip'] = "";
$myCollect['spider_mode'] = "0";
$myCollect['spider_status'] = "2";
$myCollect['spider_errlog'] = "0";
$myCollect['referer'] = "0";
$myCollect['pagecharset'] = "utf8";
$myCollect['titlerepeat'] = "0";
$myCollect['formatcontent'] = "0";
$myCollect['collectuser'] = "1";
$myCollect['urluser'] = "anjumember";
$myCollect['urlinfo'] = "http://chengdu.haozu.com/rental/broker/n/<{infoid}>";
$myCollect['contpagemode'] = "0";
$myCollect['rule']['title'] = "<h1 class=\"title f16 txt_c\" title=\"(.*)\">";
$myCollect['rule']['price'] = "租金：<em>(.*)</em>";
$myCollect['rule']['houseearm'] = "面积：(.*)平米";
$myCollect['rule']['room'] = "房型：(.*)室";
$myCollect['rule']['hall'] = "房型：\d*室(.*)厅";
$myCollect['rule']['toilet'] = "房型：\d*厅(.*)卫";
$myCollect['rule']['telephone'] = "<p class=\"tel_mobile view_prop_bg\"></p>\s*<strong>(.*)</strong>";
$myCollect['rule']['address'] = "地址：(.*) (<";
$myCollect['rule']['toward'] = "朝向：(.*)</";
$myCollect['rule']['floor1'] = "楼层：(.*)/";
$myCollect['rule']['floor2'] = "楼层：\d*/(.*)</";
$myCollect['rule']['zhuanxiu'] = "装修：(.*)</";
$myCollect['rule']['content'] = "<div class=\"content prop_inrto_text\">(.*)</div>";
$myCollect['rule']['thumb'] = "<li class=\"li_img li_icon\" bigSrc=\"(.*)\"><img";
$myCollect['rule']['housename'] = "小区：(.*)</a>";
$myCollect['rule']['thumb1'] = "<li class=\"li_img\" bigSrc=\"(.*)\"><img";
$myCollect['rule']['uid'] = "<a href=\"http://chengdu.haozu.com/shop/(.*)/\"";
$myCollect['rule']['username'] = "<strong class=\"f14\"><a href=\"(.*)\" target=\"_blank\" hidefocus=\"true\" >(.*)</a>";
$myCollect['rule']['truename'] = "<div class=\"prop_new_line\">\s*<a href=\"(.*)\" target=\"_blank\">(.*)</a>";
$myCollect['rule']['company'] = "就职于：<span class=\"\">(.*)</span>";
$myCollect['replacelist']['housename'] = "<a.+?>";
$myCollect['replacelist']['content'] = "<a.+?>##<script>.+?</script>";
$myCollect['replacelist']['thumb1'] = "<a.+?>";
$myCollect['replacelist']['thumb2'] = "<a.+?>";
$myCollect['replacelist']['company'] = "<a.+?>";
$myCollect['replacelist']['username'] = "<a.+?>";
$myCollect['replacelist']['telephone'] = "<span>.+?</span>";
$myCollect['defaultvalue']['typeid'] = "0";
$myCollect['defaultvalue']['username'] = "admin";
$myCollect['listcollect']['0']['title'] = "锦江租房";
$myCollect['listcollect']['0']['catid'] = "13";
$myCollect['listcollect']['0']['areaid'] = "2";
$myCollect['listcollect']['0']['urlpage'] = "http://chengdu.haozu.com/listing/jinjiang/ht8-l1-p<{pageid}>/";
$myCollect['listcollect']['0']['listarea'] = "<div class=\"plate\" id=\"apf_id_14_list\">(.*)/div>";
$myCollect['listcollect']['0']['infoid'] = "<dl class=\"dl_list_house clear_box\" link=\"http://chengdu.haozu.com/rental/broker/n/(\d*)\">";
$myCollect['listcollect']['0']['nextpageid'] = "++";
$myCollect['listcollect']['0']['startpageid'] = "1";
$myCollect['listcollect']['0']['maxpagenum'] = "1";

?>