<?php
$myCollect['sitename'] = "安居客";
$myCollect['siteurl'] = "http://chengdu.anjuke.com";
$myCollect['modid'] = "5";
$myCollect['apiname'] = "";
$myCollect['proxy_host'] = "";
$myCollect['proxy_port'] = "";
$myCollect['verify_mode'] = "2";
$myCollect['spider_auth'] = "123456";
$myCollect['spider_ip'] = "";
$myCollect['spider_mode'] = "0";
$myCollect['spider_status'] = "2";
$myCollect['spider_errlog'] = "0";
$myCollect['referer'] = "0";
$myCollect['pagecharset'] = "utf8";
$myCollect['titlerepeat'] = "1";
$myCollect['formatcontent'] = "0";
$myCollect['collectuser'] = "1";
$myCollect['urluser'] = "anjumember";
$myCollect['urlinfo'] = "http://chengdu.anjuke.com/prop/view/<{infoid}>?from=";
$myCollect['contpagemode'] = "0";
$myCollect['rule']['title'] = "<h1 class=\"propInfoTitle\">\s*(.*)</h1>";
$myCollect['rule']['price'] = "价：<em>(.*)</em><span>万";
$myCollect['rule']['houseearm'] = "产证面积：(.*)平米";
$myCollect['rule']['room'] = "房型：(.*)室";
$myCollect['rule']['hall'] = "房型：\d*室(.*)厅";
$myCollect['rule']['toilet'] = "房型：\d*厅(.*)卫";
$myCollect['rule']['telephone'] = "<div class=\"number\"><b>(.*)</b></div>";
$myCollect['rule']['address'] = "地址：<span id=\"text_for_school_2\" title=\"(.*)\">";
$myCollect['rule']['toward'] = "朝向：(.*)</";
$myCollect['rule']['houseyear'] = "建造年代：(.*)年";
$myCollect['rule']['floor1'] = "楼层：(.*)/";
$myCollect['rule']['floor2'] = "楼层：\d*/(.*)</";
$myCollect['rule']['zhuanxiu'] = "装修：(.*)</";
$myCollect['rule']['content'] = "</h4>-->\s*</div>(.*)<div class=\"clear\" id=\"lazy_line\">";
$myCollect['rule']['thumb'] = "<a href=\"#roompic\"><span></span><img src=\"(.*)\" title";
$myCollect['rule']['housename'] = "小区：(.*)</a>";
$myCollect['rule']['thumb1'] = "<li><a href=\"###\">(.*)50\" ref=\"(.*)\" title=";
$myCollect['rule']['thumb2'] = "<span class=\"piclink\"><a target=\"_blank\" href=\"(.*)\"><img title=\"(.*)\" alt=\"(.*)\" src=\"(.*)\" /></a>";
$myCollect['rule']['uid'] = "<a href=\"http://chengdu.anjuke.com/shop/view/(.*)\"";
$myCollect['rule']['username'] = "<div class=\"prop_new_line\">\s*<a href=\"(.*)\" target=\"_blank\">(.*)</a>";
$myCollect['rule']['truename'] = "<div class=\"prop_new_line\">\s*<a href=\"(.*)\" target=\"_blank\">(.*)</a>";
$myCollect['rule']['company'] = "公司 :  &nbsp;&nbsp;(.*)</a>";
$myCollect['replacelist']['housename'] = "<a.+?>";
$myCollect['replacelist']['content'] = "<a.+?>##<script>.+?</script>";
$myCollect['replacelist']['thumb1'] = "<a.+?>";
$myCollect['replacelist']['thumb2'] = "<a.+?>";
$myCollect['replacelist']['company'] = "<a.+?>";
$myCollect['defaultvalue']['typeid'] = "1";
$myCollect['listcollect']['0']['title'] = "锦江二手房";
$myCollect['listcollect']['0']['catid'] = "8";
$myCollect['listcollect']['0']['areaid'] = "2";
$myCollect['listcollect']['0']['urlpage'] = "http://chengdu.anjuke.com/sale/jinjiang/p<{pageid}>-t21";
$myCollect['listcollect']['0']['listarea'] = "<form name=\"batchForm\">(.*)";
$myCollect['listcollect']['0']['infoid'] = "<a id=\"prop_name_qt_prop_\d*\" href=\"http://chengdu.anjuke.com/prop/view/(\d*)\"";
$myCollect['listcollect']['0']['nextpageid'] = "++";
$myCollect['listcollect']['0']['startpageid'] = "1";
$myCollect['listcollect']['0']['maxpagenum'] = "5";

?>