<?php
$myCollect['sitename'] = "爱房网成都";
$myCollect['siteurl'] = "http://chengdu.aifang.com";
$myCollect['modid'] = "6";
$myCollect['apiname'] = "";
$myCollect['proxy_host'] = "";
$myCollect['proxy_port'] = "";
$myCollect['verify_mode'] = "2";
$myCollect['spider_auth'] = "123456";
$myCollect['spider_ip'] = "";
$myCollect['spider_mode'] = "0";
$myCollect['spider_status'] = "2";
$myCollect['spider_errlog'] = "0";
$myCollect['referer'] = "0";
$myCollect['pagecharset'] = "utf8";
$myCollect['titlerepeat'] = "1";
$myCollect['formatcontent'] = "0";
$myCollect['collectuser'] = "0";
$myCollect['urluser'] = "";
$myCollect['urlinfo'] = "http://chengdu.aifang.com/loupan/canshu-<{infoid}>.html";
$myCollect['contpagemode'] = "0";
$myCollect['rule']['title'] = "<h1 class=\"t_name\" title=\"\">(.*)</h1>";
$myCollect['rule']['address'] = "<b>楼盘地址</b>\s*<span>(.*)<a";
$myCollect['rule']['telephone'] = "<b>售楼处电话</b>\s*<span>(.*)</s";
$myCollect['rule']['tedian'] = "<b>楼盘特点</b>\s*<span>(.*)</span>";
$myCollect['rule']['price'] = "<b>住宅售价</b>\s*<span>(.*)&nbsp;";
$myCollect['rule']['selltime'] = "<em>预计开盘时间</em>\s*<span>(.*)</span>";
$myCollect['rule']['completion'] = "<em>预计交房时间</em>\s*<span>(.*)</span>";
$myCollect['rule']['company'] = "<em>开发商</em>\s*<span>(.*)</span>";
$myCollect['rule']['sell_address'] = "<em>售楼处地址</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_fitment'] = "<em>装修情况</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_year'] = "<em>产权年限</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_totalarea'] = "<em>规划面积</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_area'] = "<em>建筑面积</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_number'] = "<em>规划户数</em>\s*<span>(.*)户</span>";
$myCollect['rule']['lp_car'] = "<em>车位数</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_volume'] = "<em>容积率</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_green'] = "<em>绿化率</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_company'] = "<em>物业公司</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_costs'] = "<em>物业费</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_bus'] = "<em>公交</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_edu'] = "<em>教育</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_hospital'] = "<em>医院</em>\s*<span>(.*)</span>";
$myCollect['rule']['lp_bank'] = "<em>银行</em>\s*<span>(.*)</span>";
$myCollect['rule']['custom-buildtype'] = "<em>建筑类型</em>\s*<span>(.*)</span>";
$myCollect['pagerule']['1']['pageurl'] = "http://chengdu.aifang.com/loupan/<{infoid}>.html";
$myCollect['pagerule']['1']['thumb'] = "blank\"><img src=\"(.*)\" alt";
$myCollect['pagerule']['1']['content'] = "<p class=\"about\">(.*)</p>";
$myCollect['replacelist']['title'] = "参数";
$myCollect['replacelist']['content'] = "\\\\##本公司以加工(.*)背心等@@这是替换过的";
$myCollect['replacelist']['thumb1'] = "summ@@310x310";
$myCollect['replacelist']['thumb2'] = "summ@@310x310";
$myCollect['replacelist']['price'] = "元/平米";
$myCollect['replacelist']['lp_area'] = "平米";
$myCollect['replacelist']['lp_totalarea'] = "平米";
$myCollect['replacelist']['lp_year'] = "年";
$myCollect['replacelist']['lp_car'] = "个 (.*)";
$myCollect['replacelist']['lp_green'] = "%";
$myCollect['replacelist']['lp_costs'] = "元/平米/月";
$myCollect['replacelist']['lp_volume'] = "公寓:";
$myCollect['defaultvalue']['typeid'] = "0";
$myCollect['defaultvalue']['username'] = "aijiacms";
$myCollect['defaultvalue']['isnew'] = "1";
$myCollect['listcollect']['0']['title'] = "锦江新房";
$myCollect['listcollect']['0']['catid'] = "1";
$myCollect['listcollect']['0']['areaid'] = "2";
$myCollect['listcollect']['0']['urlpage'] = "http://chengdu.aifang.com/loupan/jinjiang/s?m=1&p=<{pageid}>&p1=904";
$myCollect['listcollect']['0']['listarea'] = "<form name=\"batchForm\">(.*)";
$myCollect['listcollect']['0']['infoid'] = "<div class=\"loupan_list_item\" id=\"loupan_item_(\d*)\"";
$myCollect['listcollect']['0']['nextpageid'] = "++";
$myCollect['listcollect']['0']['startpageid'] = "1";
$myCollect['listcollect']['0']['maxpagenum'] = "1";

?>