<?php
$names = array (
  'about' => '关于网站',
  'area' => '地区',
  'article' => '文章',
  'brand' => '品牌',
  'buy' => '求购',
  'category' => '分类',
  'charge' => '充值',
  'chip-album' => '公用图片展示',
  'chip-contact' => '公用联系方式',
  'chip-content' => '公用内容显示',
  'chip-search' => '公用搜索',
  'company' => '公司',
  'exhibit' => '展会',
  'footer' => '页脚',
  'group' => '团购',
  'header' => '页头',
  'index' => '首页',
  'info' => '信息',
  'job' => '招聘',
  'know' => '知道',
  'login' => '登录',
  'mall' => '商城',
  'member' => '会员中心',
  'message' => '站内信',
  'message_send' => '发送站内信',
  'msg' => '信息提示',
  'photo' => '图库',
  'quote' => '报价',
  'sell' => '供应',
  'video' => '视频',
);
?>