<?php
$names = array (
  'about' => '关于网站',
  'area' => '地区',
  'article' => '文章',
  'brand' => '品牌',
  'buy' => '求购',
  'category' => '分类',
  'charge' => '充值',
  'company' => '公司',
  'contact' => '联系内容',
  'content' => '信息内容',
  'exhibit' => '展会',
  'footer' => 'WAP页脚',
  'group' => '团购',
  'header' => 'WAP页头',
  'index' => 'WAP首页',
  'info' => '信息',
  'job' => '招聘',
  'know' => '知道',
  'login' => '登录',
  'mall' => '商城',
  'message' => '站内信',
  'message_send' => '发送站内信',
  'msg' => '信息提示',
  'photo' => '图库',
  'quote' => '报价',
  'sell' => '供应',
  'video' => '视频',
);
?>